name: destiny2_app
description: The Destiny 2 app in Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  built_collection: ^5.1.1
  built_value: ^8.4.2
  http: ^0.13.5
  shared_preferences: ^2.0.15
  dynamic_color: ^1.5.4
  animations: ^2.0.7
  webview_flutter: ^4.0.1
  sqflite: ^2.2.2
  path: ^1.8.2
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  built_value_generator: ^8.4.2

flutter:
  uses-material-design: true

  fonts:
    - family: Zen Kaku Gothic Antique
      fonts:
        - asset: fonts/ZenKakuGothicAntique.ttf
  
  assets:
    - fonts/